esp32:
  board: esp32dev
  framework:
    type: esp-idf  # or arduino

one_wire:
  - platform: gpio
    pin: GPIO02
    id: dallas_bus_1
  - platform: gpio
    pin: GPIO04
    id: dallas_bus_2

# Individual sensors
sensor:
  - platform: dallas_temp
    #index: 0
    address: ${dallas_sensor_address_1}
    name: ${thermostate_friendly_name_1} Temperature
    id: temperature_1
    one_wire_id: dallas_bus_${dallas_sensor_bus_1}
    update_interval: 10s
    filters:
      delta: 0.5
  - platform: dallas_temp
    #index: 0
    address: ${dallas_sensor_address_2}
    name: ${thermostate_friendly_name_2} Temperature
    id: temperature_2
    one_wire_id: dallas_bus_${dallas_sensor_bus_2}
    update_interval: 10s
    filters:
      delta: 0.5

output:
  - platform: gpio
    pin: GPIO22
    id: relay_1_out
  - platform: gpio
    pin: GPIO23
    id: relay_2_out
  - platform: gpio
    pin: GPIO05
    id: led_out
    
switch:
  - platform: output
    name: ${thermostate_friendly_name_1} Relay
    id: relay_1
    output: relay_1_out
    on_turn_on:
    - light.turn_on: led
    on_turn_off:
      if:
        condition:
          switch.is_off: relay_2
        then:
        - light.turn_off: led
  - platform: output
    name: ${thermostate_friendly_name_2} Relay
    id: relay_2
    output: relay_2_out
    on_turn_on:
    - light.turn_on: led
    on_turn_off:
      if:
        condition:
          switch.is_off: relay_1
        then:
        - light.turn_off: led

light:
  - platform: binary
    name: Led
    id: led
    output: led_out

climate:
  - platform: bang_bang
    sensor: temperature_1
    name: ${thermostate_friendly_name_1}
    id: climate_1
    default_target_temperature_low: ${default_target_temperature_low_1} °C
    default_target_temperature_high: ${default_target_temperature_high_1} °C
    visual:
      min_temperature: ${min_temperature} °C
      max_temperature: ${max_temperature} °C
      temperature_step: ${temperature_step} °C

    cool_action:
      - switch.turn_on: relay_1
    idle_action:
      - switch.turn_off: relay_1
  - platform: bang_bang
    sensor: temperature_2
    name: ${thermostate_friendly_name_2}
    id: climate_2
    default_target_temperature_low: ${default_target_temperature_low_2} °C
    default_target_temperature_high: ${default_target_temperature_high_2} °C
    visual:
      min_temperature: ${min_temperature} °C
      max_temperature: ${max_temperature} °C
      temperature_step: ${temperature_step} °C

    cool_action:
      - switch.turn_on: relay_2
    idle_action:
      - switch.turn_off: relay_2