esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev

dallas:
  - pin: GPIO02
    update_interval: 1s

# Individual sensors
sensor:
  - <<: !include ../includes/uptime-sensor.yaml
  - platform: dallas
    index: 0
    #address: 0x1c0000031edd2a28
    name: ${sensorname} Temperature
    id: temperature
    filters:
      delta: 0.5

output:
  - platform: gpio
    pin: GPIO22
    id: relay_1_out
  - platform: gpio
    pin: GPIO05
    id: led_out
    
switch:
  - platform: output
    name: ${sensorname} Relay 1
    output: relay_1_out
    id: relay_1
    on_turn_on:
    - light.turn_on: led
    on_turn_off:
    - light.turn_off: led

light:
  - platform: binary
    name: ${sensorname} Led
    id: led
    output: led_out

climate:
  - platform: bang_bang
    sensor: temperature
    name: ${sensorname}
    default_target_temperature_low: ${default_target_temperature_low_1} °C
    default_target_temperature_high: ${default_target_temperature_high_1} °C
    visual:
      min_temperature: ${min_temperature} °C
      max_temperature: ${max_temperature} °C
      temperature_step: ${temperature_step} °C

    cool_action:
      - switch.turn_on: relay_1
    idle_action:
      - switch.turn_off: relay_1