esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  build_path: build/${devicename}

sensor:
  - <<: !include ../includes/uptime-sensor.yaml

switch:
  - platform: gpio
    pin: D2
    #name: "DoorRelay Test-Only"
    restore_mode: ALWAYS_OFF 
    id: relay
    
  - platform: template
    name: "${devicename}_open_door"
    id: open_door
    icon: "mdi:gate"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 2000ms
    - switch.turn_off: relay
    
  - platform: template
    name: "Ring Homematic Bell"
    internal: true
    id: homematic_bell
    turn_on_action:
    #Bell on
    - homeassistant.service:
        service: notify.html5
        data:
          entity_id: switch.gong_2
    #Led on
    - homeassistant.service:
        service: notify.html5
        data:
          entity_id: switch.gong_1

binary_sensor:
  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename}_bell"
    device_class: sound
    filters:
      - delayed_off: 1000ms
    on_release:
    - switch.turn_on: homematic_bell
    on_multi_click:
    - timing:
        - ON for at least 2s
      then:
      - switch.turn_on: open_door