substitutions:
  # time to press key before opening the door
  bell_key_delay: 1000ms

  door_addr: 0x02
  
  #client_1_addr: 
  client_1_name: client_1
  #client_2_addr: 
  client_2_name: client_2

esp32:
  board: esp32dev
  flash_size: 8MB


# esphome:
#   platformio_options:
#     build_flags: -DCONFIG_GPTIMER_CTRL_FUNC_IN_IRAM=1

external_components:
  - source:
      type: local
      path: devices/pcb-siedle-bus/components

siedle_inhome_bus:
  carrier_pin: GPIO16
  rx_pin: 
    number: GPIO17
    inverted: true
  load_pin: GPIO13
  tx_pin: 
    number: GPIO14
    inverted: true
  dump: true

binary_sensor:
  # Bell client 1
  - platform: siedle_inhome_bus
    name: bell_${client_1_name}
    icon: "mdi:bell"
    device_class: sound
    message:
      command: &BELL_CMD 0x09
      source: ${door_addr}
      destination: ${client_1_addr}
    filters:
      - delayed_off: ${bell_key_delay}
    on_release:
    - button.press: my_open_button
  # Bell client 2
  - platform: siedle_inhome_bus
    name: bell_${client_2_name}
    icon: "mdi:bell"
    device_class: sound
    message:
      command: *BELL_CMD
      source: ${door_addr}
      destination: ${client_2_addr}
    filters:
      - delayed_off: ${bell_key_delay}

button:
  # Open
  - platform: siedle_inhome_bus
    name: open
    id: my_open_button
    icon: "mdi:gate"
    message:
      command: &OPEN_COMMAND 0x0C
      source: ${client_1_addr}
      destination: ${door_addr}
  # Light
  - platform: siedle_inhome_bus
    name: light
    id: my_light_button
    icon: "mdi:light"
    message:
      command: &LIGHT_COMMAND 0x2C
      source: ${client_1_addr}
      destination: &DOORLIGHT 0x00
  # Bell client 1
  - platform: siedle_inhome_bus
    name: trigger_bell_${client_1_name}
    icon: "mdi:bell"
    message:
      command: *BELL_CMD
      source: ${door_addr}
      destination: ${client_1_addr}
  # Bell client 2
  - platform: siedle_inhome_bus
    name: trigger_bell_${client_2_name}
    icon: "mdi:bell"
    message:
      command: *BELL_CMD
      source: ${door_addr}
      destination: ${client_2_addr}
