substitutions:
  # time to press key before opening the door
  bell_key_delay: 1000ms

esp32:
  board: esp32dev
  flash_size: 8MB

esphome:
  platformio_options:
    build_flags: -DCONFIG_GPTIMER_CTRL_FUNC_IN_IRAM=1

external_components:
  - source:
      type: local
      path: devices/pcb-siedle-bus/components

siedle_inhome_bus:
  carrier_pin: GPIO16
  rx_pin: 
    number: GPIO17
    inverted: true
  load_pin: GPIO13
  tx_pin: 
    number: GPIO14
    inverted: true
  dump: true

binary_sensor:
  - platform: siedle_inhome_bus
    name: bell_small
    icon: "mdi:bell"
    device_class: sound
    message:
      # 0x44A210A0
      command: &BELL_CMD 0x09
      source: &DOOR 0x02
      destination: &SMALL_FLAT 0x08
    filters:
      - delayed_off: ${bell_key_delay}
    on_release:
    - button.press: my_open_button
  - platform: siedle_inhome_bus
    name: bell_large
    icon: "mdi:bell"
    device_class: sound
    message:
      # 0x44FA10A0
      command: *BELL_CMD
      source: *DOOR
      destination: &LARGE_FLAT 0x1E
    filters:
      - delayed_off: ${bell_key_delay}
    on_release:
    - button.press: my_open_button

button:
  - platform: siedle_inhome_bus
    name: open
    id: my_open_button
    icon: "mdi:gate"
    message:
      # 0x460A1220
      command: &OPEN_COMMAND 0x0C
      source: *SMALL_FLAT
      destination: *DOOR
  - platform: siedle_inhome_bus
    name: trigger_bell_small
    icon: "mdi:bell"
    message:
      # 0x44A210A0
      command: *BELL_CMD
      source: *DOOR
      destination: *SMALL_FLAT
  - platform: siedle_inhome_bus
    name: trigger_bell_large
    icon: "mdi:bell"
    message:
      # 0x44FA10A0
      command: *BELL_CMD
      source: *DOOR
      destination: *LARGE_FLAT
