substitutions:
  # time to press key before opening the door
  bell_key_delay: 1000ms
  # time to keep opening the door
  open_time: 2000ms

esp8266:
  board: d1_mini

switch:
  - platform: gpio
    pin: D2
    #name: "DoorRelay Test-Only"
    restore_mode: ALWAYS_OFF 
    id: my_relay

button:    
  - platform: template
    name: "Open button"
    id: my_open_button
    icon: "mdi:gate"
    on_press:
    - switch.turn_on: my_relay
    - delay: ${open_time}
    - switch.turn_off: my_relay
    
  - platform: template
    name: "Ring Homematic Bell"
    internal: true
    id: my_homematic_bell
    on_press:
    #Bell on
    - homeassistant.service:
        service: notify.html5
        data:
          entity_id: switch.gong_2
    #Led on
    - homeassistant.service:
        service: notify.html5
        data:
          entity_id: switch.gong_1

binary_sensor:
  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    name: "Bell key"
    id: my_bell_key
    device_class: sound
    filters:
      - delayed_off: ${bell_key_delay}
    on_release:
    - button.press: my_homematic_bell
    on_multi_click:
    - timing:
        - ON for at least 2s
      then:
      - button.press: my_open_button