substitutions:
  devicename: cam01_unused
  friendly_name: Camera 01
  wifi_ip: "192.168.10.33"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  #device: !include devices/interphone-siedle/v1.yaml

esphome:
    name: my-cam
    platform: ESP32
    board: esp32dev

esp32_camera:
  name: "My Cam"
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 15 fps   
  idle_framerate: 0.05 fps 
  resolution: 1280x1024
  jpeg_quality: 15

# OV5640
# esp32_camera:
#   name: ESPcam
#   external_clock:
#     pin: GPIO15
#     frequency: 12MHz
#   i2c_pins:
#     sda: GPIO22
#     scl: GPIO23
#   data_pins: [GPIO2, GPIO14, GPIO35, GPIO12, GPIO27, GPIO33, GPIO34, GPIO39]
#   vsync_pin: GPIO18
#   href_pin: GPIO36
#   pixel_clock_pin: GPIO26
#   reset_pin: GPIO5
#   resolution: 1280x1024
#   jpeg_quality: 15
#   vertical_flip: False

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

switch:
  - platform: gpio
    name: "My Cam flash"
    pin: 4