substitutions:
  devicename: esphome_minimal
  sensorname: esphome_minimal
  wifi_ip: "192.168.2.2"

<<: !include t-common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

sensor:
- platform: uptime
  name: "${devicename}_sensor"
  filters:
    - lambda: return x / 3600.0;
  unit_of_measurement: "hours"
  accuracy_decimals: 2
  update_interval: !secret uptime_update_interval