substitutions:
  devicename: esphome_minimal
  sensorname: esphome_minimal
  wifi_ip: "192.168.2.2"

<<: !include t-common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

sensor:
- <<: !include t-uptime-sensor.yaml