substitutions:
  devicename: interphone
  sensorname: corridor_interphone
  upper_devicename: Interphone Siedle HT402
  wifi_ip: "192.168.2.11"

<<: !include t-common.yaml
<<: !include devices/interphone/v1.yaml