substitutions:
  devicename: interphone_small_flat
  friendly_name: Short Corridor Interphone
  wifi_ip: "192.168.2.11"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-siedle-bus/v1.yaml