substitutions:
  devicename: interphone_large_flat
  friendly_name: Long Corridor Interphone
  wifi_ip: "192.168.0.55"

  client_1_addr: 0x1E
  client_1_name: large_flat

  client_2_addr: 0x08
  client_2_name: small_flat

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-siedle-bus/v1.yaml