substitutions:
  devicename: l01_dani_lights_commode
  sensorname: Leds in kids commode
  wifi_ip: "192.168.2.17"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285
  #arduino_version: 2.4.2
  build_path: build/${devicename}

light:
  - platform: cwww
    name: "Dani Commode"
    cold_white: output_bottom_cold
    warm_white: output_bottom_warm
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
  - platform: cwww
    name: "Dani Shelves"
    cold_white: output_top_cold
    warm_white: output_top_warm
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K

output:
  - platform: esp8266_pwm
    id: output_bottom_cold
    pin: GPIO05
    max_power: 100%
  - platform: esp8266_pwm
    id: output_bottom_warm
    pin: GPIO12
    max_power: 100%
  - platform: esp8266_pwm
    id: output_top_warm
    pin: GPIO13
    max_power: 100%
  - platform: esp8266_pwm
    id: output_top_cold
    pin: GPIO15
    max_power: 100%
