substitutions:
  devicename: l03-workroom-1
  friendly_name: Workroom computer and workroom leds
  light_1: Computers
  light_2: Window
  wifi_ip: "192.168.0.2"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1.yaml
