substitutions:
  devicename: l08-guestroom-leds-1
  friendly_name: Guestroom left front leds
  pwm_frequency: "1000 Hz"
  light_1: Left
  light_2: Front
  wifi_ip: 192.168.0.6

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1_redbroke.yaml