substitutions:
  devicename: l08_guestroom_leds_1
  sensorname: guestroom leds
  light_1: left
  light_2: front
  wifi_ip: "192.168.0.6"
  pwm_frequency: "100 Hz"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1.yaml