substitutions:
  devicename: l10_guestroom_leds_3
  sensorname: guestroom leds
  light_1: unused
  light_2: back
  wifi_ip: "192.168.0.8"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1.yaml