substitutions:
  devicename: l11_bedroom_leds_1
  sensorname: bedroom leds front
  wifi_ip: 192.168.0.9
  pwm_frequency: "1000 Hz"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/rgbwcw.yaml