substitutions:
  devicename: l12-bedroom-leds-2
  friendly_name: Bedroom right left leds
  pwm_frequency: "100 Hz"
  light_1: Right
  light_2: Left
  wifi_ip: 192.168.0.10

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-led_lights/ww_ww_v2.yaml
