substitutions:
  devicename: l12_bedroom_leds_2
  sensorname: bedroom leds
  light_1: right
  light_2: left
  wifi_ip: 192.168.0.10
  pwm_frequency: "1000 Hz"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1.yaml