substitutions:
  devicename: l16-livingroom-leds-3
  friendly_name: Livingroom left and back leds
  light_1: Left
  light_2: Back
  wifi_ip: 192.168.0.15
  pwm_frequency: "200 Hz"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-led_lights/ww_ww_v2.yaml

