substitutions:
  devicename: l18-alicia-leds
  sensorname: leds alicia leds
  light_1: unused
  light_2: ceiling
  wifi_ip: 192.168.0.17
  pwm_frequency: "1000 Hz"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1.yaml