substitutions:
  wifi_ip: 192.168.104.10
  devicename: l24-pueblo-leds-edu
  friendly_name: Pueblo leds Edu
  delayed_off: "300ms"
  led1_name: bed
  led1_num_leds: "39"
  led2_name: unused
  led2_num_leds: "10"
  rotate_effect: !include devices/includes/lights-effects/rotate_effects.yaml

packages:
  #Include location specific settings
  location: !include locations/pueblo.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-led_rf/v1.yaml


light:
  - platform: partition
    id: led1_partition1
    name: "left bed"
    segments:
      - id: led1
        from: 34
        to: 38
    effects:
      !include devices/includes/lights-effects/addressable_effects.yaml

  - platform: partition
    id: led1_partition2
    name: "right bed"
    segments:
      - id: led1
        from: 0
        to: 4
    effects:
      !include devices/includes/lights-effects/addressable_effects.yaml

binary_sensor:
  # Left pushbutton (ventana)
  - platform: remote_receiver
    name: "left_pushbotton left"
    rc_switch_raw:
      code: "111011000011111111010100"
      protocol: 6
    filters:
    - delayed_off: ${delayed_off}
    on_press:
      then:
      - light.toggle: led1_partition1
  - platform: remote_receiver
    name: "left_pushbotton center"
    rc_switch_raw:
      code: "111011000011111111011000"
      protocol: 6
    filters:
    - delayed_off: ${delayed_off}
    on_press:
      then:
      - lambda: |-
          auto my_led = id(led1);
          ${rotate_effect}
  - platform: remote_receiver
    name: "left_pushbotton right"
    rc_switch_raw:
      code: "111011000011111111010010"
      protocol: 6
    filters:
    - delayed_off: ${delayed_off}
    on_press:
      then:
      - light.toggle: led1
  # Right pushbutton (armario)
  - platform: remote_receiver
    name: "right_pushbotton left"
    rc_switch_raw:
      code: "110100100000010100000100"
      protocol: 6
    filters:
    - delayed_off: ${delayed_off}
    on_press:
      then:
      - light.toggle: led1_partition2
  - platform: remote_receiver
    name: "right_pushbotton center"
    rc_switch_raw:
      code: "110100100000010100001000"
      protocol: 6
    filters:
    - delayed_off: ${delayed_off}
    on_press:
      then:
      - lambda: |-
          auto my_led = id(led1);
          ${rotate_effect}
  - platform: remote_receiver
    name: "right_pushbotton right"
    rc_switch_raw:
      code: "110100100000010100000010"
      protocol: 6
    filters:
    - delayed_off: ${delayed_off}
    on_press:
      then:
      - light.toggle: led1