substitutions:
  #This is the name for device in wifi
  devicename: m1-casa96-meter
  #Sensor name in home assistant and web server
  friendly_name: Casa96 meter
  #IP for device
  wifi_ip: "192.168.0.29"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-meter/double_gas_electrictiy_v1.yaml