substitutions:
  devicename: padres_rgbw
  sensorname: padres_rgbw
  wifi_ip: "192.168.3.12"

<<: !include t-common-casa128.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

sensor:
  - <<: !include t-uptime-sensor.yaml

time:
  - platform: sntp
    timezone: Europe/Berlin
    # ...
    on_time:

      # Every morning
      - seconds: 0
        minutes: 0
        hours: 8
        then:
          - light.turn_on: 
              id: ${devicename}_light
              brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              white: 100%

      # Every morning on weekdays
      - seconds: 0
        minutes: 0
        hours: 23
        then:
          - light.turn_on:
              id: ${devicename}_light
              brightness: 20%
              red: 0%
              green: 20%
              blue: 0%
              white: 0%

light:
  - platform: rgbw
    name: ${sensorname}
    id: ${devicename}_light
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ALWAYS_OFF
    effects:
      - strobe: 
          name: Strobe
          #colors:
            #- state: True
              #brightness: 100%
              #red: 100%
              #green: 90%
              #blue: 0%
              #duration: 500ms
            #- state: False
              #duration: 250ms
            #- state: True
              #brightness: 100%
              #red: 0%
              #green: 100%
              #blue: 0%
              #duration: 500ms
      - flicker:
          name: Flicker
          #alpha: 95%
          #intensity: 1.5%
      - lambda:
           name: MyCustomEffect
           update_interval: 1s
           lambda: |-
            static int state = 0;
            auto call = id(${devicename}_light).turn_on();
            // Transtion of 1000ms = 1s
            call.set_transition_length(1000);
            if (state == 0) {
              call.set_rgb(1.0, 1.0, 1.0);
            } else if (state == 1) {
              call.set_rgb(1.0, 0.0, 1.0);
            } else if (state == 2) {
              call.set_rgb(0.0, 0.0, 1.0);
            } else {
              call.set_rgb(1.0, 0.0, 0.0);
            }
            call.perform();
            state += 1;
            if (state == 4)
              state = 0;
      - lambda:
           name: Breathing
           update_interval: 16s
           lambda: |-
            static int state = 0;
            static int color = 1;
            auto call = id(${devicename}_light).turn_on(); //the id of your light
            call.set_transition_length(15000);
            if (state == 0) 
            {
             call.set_brightness(1.0);
            }
             else if (state == 1)
            {
             call.set_brightness(0.01);
            }
             call.perform();
             state ++;
             if (state == 2){
             state = 0;
             }
      - lambda:
           name: RGB_Breathing
           update_interval: 16s #Finetune to your liking with the transition lenght below
           lambda: |-
            #define Color1 1.0, 0.0, 0.0 //These are the colors defined, feel free to change or extend the list
            #define Color2 1.0, 0.5, 0.0 //if you extend the list, dont forget to add them in the switch loop below
            #define Color3 1.0, 1.0, 0.0 //and remember to adjust the reset counter at the bottom
            #define Color4 0.5, 1.0, 0.0
            #define Color5 0.0, 1.0, 0.0
            #define Color6 0.0, 1.0, 0.5
            #define Color7 0.0, 1.0, 1.0
            #define Color8 0.0, 0.5, 1.0
            #define Color9 0.0, 0.0, 1.0
            #define Color10 0.5, 0.0, 1.0
            #define Color11 0.5, 0.0, 1.0
            #define Color12 1.0, 0.0, 0.5
            static int state = 0;
            static int color = 1;
            auto call = id(${devicename}_light).turn_on(); //put the id for your light in here
            call.set_transition_length(15000);
            if (state == 0) 
            {
             call.set_brightness(0.01);
             
            }
             else if (state == 1)
            {
               switch(color)
               {
                 case 1: call.set_rgb(Color1);
                         break;
                 case 2: call.set_rgb(Color2);
                         break;
                 case 3: call.set_rgb(Color3);
                         break;
                 case 4: call.set_rgb(Color4);
                         break;
                 case 5: call.set_rgb(Color5);
                         break;
                 case 6: call.set_rgb(Color6);
                         break;
                 case 7: call.set_rgb(Color7);
                         break;
                 case 8: call.set_rgb(Color8);
                         break;
                 case 9: call.set_rgb(Color9);
                         break;
                 case 10: call.set_rgb(Color10);
                          break;
                 case 11: call.set_rgb(Color11);
                          break;
                 case 12: call.set_rgb(Color12);
                          break;
               }
              call.set_brightness(1.0);
            }
             
             state ++;
             if (state == 2){
             state = 0;
             }
             color++;
             if(color == 7)
             {
               color = 1;
             }
             call.perform();
             
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO12
    max_power: 100%
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO5
    max_power: 100%
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
    max_power: 100%
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO15
    max_power: 100%

remote_receiver:
  pin:
    number: GPIO04
    inverted: true
  dump: nec

binary_sensor:
- platform: remote_receiver
  name: "Button UP"
  internal: True
  nec:
    address: 0x00FF
    command: 0x906F
  on_press:
    then:
      - light.dim_relative:
          id: ${devicename}_light
          relative_brightness: 10% 
- platform: remote_receiver
  name: "Button DOWN"
  internal: True
  nec:
    address: 0x00FF
    command: 0xB847
  on_press:
    then:
      - light.dim_relative:
          id: ${devicename}_light
          relative_brightness: -10%
- platform: remote_receiver
  name: "Button OFF"
  internal: True
  nec:
    address: 0x00FF
    command: 0xF807
  on_press:
    then:
      - light.turn_off: ${devicename}_light
- platform: remote_receiver
  name: "Button ON"
  internal: True
  nec:
    address: 0x00FF
    command: 0xB04F
  on_press:
    then:
      - light.turn_on: ${devicename}_light
      
- platform: remote_receiver
  name: "Button Red"
  internal: True
  nec:
    address: 0x00FF
    command: 0x9867
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 100%
          green: 0%
          blue: 0%
          white: 0%

- platform: remote_receiver
  name: "Button Red->yellow-1"
  internal: True
  nec:
    address: 0x00FF
    command: 0xE817
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 80%
          green: 40%
          blue: 0%
          white: 0%
- platform: remote_receiver
  name: "Button Red->yellow-2"
  internal: True
  nec:
    address: 0x00FF
    command: 0x02FD
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 100%
          green: 50%
          blue: 0%
          white: 0%
- platform: remote_receiver
  name: "Button Red->yellow-3"
  internal: True
  nec:
    address: 0x00FF
    command: 0x50AF
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 100%
          green: 70%
          blue: 40%
          white: 0%
- platform: remote_receiver
  name: "Button Red->yellow-4"
  internal: True
  nec:
    address: 0x00FF
    command: 0x38C7
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 100%
          green: 100%
          blue: 0%
          white: 0%
      
- platform: remote_receiver
  name: "Button Green"
  internal: True
  nec:
    address: 0x00FF
    command: 0xD827
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 0%
          green: 100%
          blue: 0%
          white: 0%

- platform: remote_receiver
  name: "Button Green->Blue-1"
  internal: True
  nec:
    address: 0x00FF
    command: 0x48B7
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 50%
          green: 100%
          blue: 0%
          white: 0%
- platform: remote_receiver
  name: "Button Green->Blue-2"
  internal: True
  nec:
    address: 0x00FF
    command: 0x32CD
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 0%
          green: 100%
          blue: 50%
          white: 0%
- platform: remote_receiver
  name: "Button Green->Blue-3"
  internal: True
  nec:
    address: 0x00FF
    command: 0x7887
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 0%
          green: 100%
          blue: 80%
          white: 0%
- platform: remote_receiver
  name: "Button Green->Blue-4"
  internal: True
  nec:
    address: 0x00FF
    command: 0x28D7
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 0%
          green: 80%
          blue: 100%
          white: 0%
      
- platform: remote_receiver
  name: "Button Blue"
  internal: True
  nec:
    address: 0x00FF
    command: 0x8877
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 0%
          green: 0%
          blue: 100%
          white: 0%

- platform: remote_receiver
  name: "Button Blue->Pink-1"
  internal: True
  nec:
    address: 0x00FF
    command: 0x6897
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 30%
          green: 0%
          blue: 100%
          white: 0%
- platform: remote_receiver
  name: "Button Blue->Pink-2"
  internal: True
  nec:
    address: 0x00FF
    command: 0x20DF
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 50%
          green: 0%
          blue: 100%
          white: 0%
- platform: remote_receiver
  name: "Button Blue->Pink-3"
  internal: True
  nec:
    address: 0x00FF
    command: 0x708F
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 80%
          green: 0%
          blue: 100%
          white: 0%
- platform: remote_receiver
  name: "Button Blue->Pink-4"
  internal: True
  nec:
    address: 0x00FF
    command: 0xF00F
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 100%
          green: 0%
          blue: 100%  
          white: 0%    

- platform: remote_receiver
  name: "Button White"
  internal: True
  nec:
    address: 0x00FF
    command: 0xA857
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: none
          #brightness: 100%
          red: 100%
          green: 100%
          blue: 100%
          white: 100%

- platform: remote_receiver
  name: "Button Flash"
  internal: True
  nec:
    address: 0x00FF
    command: 0xB24D
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: Flicker 
          
- platform: remote_receiver
  name: "Button Strobe"
  internal: True
  nec:
    address: 0x00FF
    command: 0x00FF
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: Strobe 

- platform: remote_receiver
  name: "Button Fade"
  internal: True
  nec:
    address: 0x00FF
    command: 0x58A7
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: Breathing

- platform: remote_receiver
  name: "Button Smooth"
  internal: True
  nec:
    address: 0x00FF
    command: 0x30CF
  on_press:
    then:
      - light.turn_on:
          id: ${devicename}_light
          effect: RGB_Breathing          

