substitutions:
  devicename: power_s12_algo
  sensorname: room_switch_algo
  wifi_ip: "192.168.2.212"

  restore_mode: RESTORE_DEFAULT_ON
  wattage_calibration1: "1 -> 1"
  wattage_calibration2: "2 -> 2"
  amperage_calibration1: "1 -> 1"
  amperage_calibration2: "2 -> 2"
  voltage_calibration1: "1 -> 1"
  voltage_calibration2: "2 -> 2"

<<: !include t-common.yaml
<<: !include devices/gosund.yaml