substitutions:
  devicename: power_s5_heater
  sensorname: guestroom_heater
  wifi_ip: "192.168.2.16"
  
  restore_mode: RESTORE_DEFAULT_OFF 
  wattage_calibration1: "1 -> 1"
  wattage_calibration2: "2 -> 2"
  amperage_calibration1: "1 -> 1"
  amperage_calibration2: "2 -> 2"
  voltage_calibration1: "1 -> 1"
  voltage_calibration2: "2 -> 2"

<<: !include t-gosund.yaml