substitutions:
  # Green
  devicename: s13-legos-shelves
  friendly_name: Shelves legos
  wifi_ip: "192.168.0.24"

  restore_mode: RESTORE_DEFAULT_ON

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/pcb-power-usb/v2.yaml

  #Include lights
  output_1: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 1
      name: "AT-AT"
  output_2: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 2
      name: "s2"
  output_3: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 3
      name: "Tree"
  output_4: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 4
      name: "Castle"
  output_5: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 5
      name: "Cantine"
  output_6: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 6
      name: "Longneck"
  output_7: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 7
      name: "Cactus"
  output_8: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 8
      name: "MoonLanding"
