substitutions:
  # Green
  devicename: s13-legos-shelves
  sensorname: legos shelves
  wifi_ip: "192.168.0.24"

  restore_mode: RESTORE_DEFAULT_ON

  switch_1: castle
  switch_2: AT-AT
  switch_3: tree
  switch_4: s4
  switch_5: s5
  switch_6: s6
  switch_7: s7
  switch_8: s8

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/pcb-power-usb/v1.yaml