substitutions:
  # Blue
  devicename: s14-legos-ceiling
  friendly_name: Ceiling legos
  wifi_ip: "192.168.0.25"

  restore_mode: RESTORE_DEFAULT_ON

  switch_1: Millennium falcon
  switch_2: Tie right
  switch_3: Tie left
  switch_4: Kylo Rens Ship
  switch_5: Chromecast
  switch_6: Destroyer
  switch_7: s7
  switch_8: s8

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/pcb-power-usb/v2.yaml

  #Include lights
  output_1: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 1
      name: "Millennium falcon"
  output_2: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 2
      name: "Tie right"
  output_3: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 3
      name: "Tie left"
  output_4: !include
    file: devices/pcb-power-usb/includes/light_v1.yaml
    vars:
      id: 4
      name: "Kylo Rens Ship"
  output_5: !include
    file: devices/pcb-power-usb/includes/switch_v1.yaml
    vars:
      id: 5
      name: "Chromecast"
  output_6: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 6
      name: "Destroyer"
  output_7: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 7
      name: "s7"
  output_8: !include
    file: devices/pcb-power-usb/includes/dimmer_v1.yaml
    vars:
      id: 8
      name: "s8"
