substitutions:
  # Red
  devicename: s18-corridor-breaker-left
  sensorname: corridor breaker left
  wifi_ip: "192.168.10.169"

  relay_1: Dani
  relay_2: Kitchen
  relay_3: Terrace
  relay_4: Rooms
  restore_mode: RESTORE_DEFAULT_ON

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/shelly/pro4pm/base_v1.yaml