substitutions:
  # Red
  devicename: s19-corridor-breaker-right
  sensorname: corridor breaker right
  wifi_ip: "192.168.10.71"

  relay_1: Unused_1
  relay_2: Network Box
  relay_3: Bathroom
  relay_4: Corridor
  restore_mode: RESTORE_DEFAULT_ON

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/shelly/pro4pm/base_v1.yaml