substitutions:
  devicename: s2_nas
  sensorname: Living Room Nas
  wifi_ip: "192.168.2.22"

  restore_mode: RESTORE_DEFAULT_ON
  wattage_calibration1: "1 -> 1"
  wattage_calibration2: "2 -> 2"
  amperage_calibration1: "1 -> 1"
  amperage_calibration2: "2 -> 2"
  voltage_calibration1: "1 -> 1"
  voltage_calibration2: "2 -> 2"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/power-gosund/v1.yaml