substitutions:
  devicename: s27-taller-breaker-left
  friendly_name: Interruptor izquierdo taller
  wifi_ip: 192.168.9.27

  relay_1: relay_1
  relay_2: relay_2
  relay_3: relay_3
  relay_4: relay_4
  restore_mode: RESTORE_DEFAULT_ON

packages:
  #Include location specific settings
  location: !include locations/pueblo.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/shelly/pro4pm/base_v1.yaml