substitutions:
  devicename: sidle_large
  upper_devicename: SidleLarge

<<: !include .common.yaml

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini


switch:
  - platform: gpio
    pin: D2
    #name: "DoorRelay Test-Only"
    restore_mode: ALWAYS_OFF 
    id: relay
    
  - platform: template
    name: "Open Door"
    id: open_door
    icon: "mdi:gate"
    turn_on_action:
    - switch.turn_on: relay
    - delay: 2000ms
    - switch.turn_off: relay
    
  - platform: template
    name: "Homematic Bell"
    id: homematic_bell
    turn_on_action:
      #Light on
      - mqtt.publish:
          topic: "hm-rpc/0/GEQ0149310/1/STATE/set"
          payload: "true"
      #Light off
      - mqtt.publish:
          topic: "hm-rpc/0/GEQ0149310/2/STATE/set"
          payload: "true"

binary_sensor:
  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
      inverted: True
    name: "Bell"
    device_class: sound
    filters:
      - delayed_off: 1000ms
    on_release:
    - switch.turn_on: homematic_bell
    on_multi_click:
    - timing:
        - ON for at least 2s
      then:
      - switch.turn_on: open_door

text_sensor:
    
  #Small Flat Bell  
  - platform: mqtt_subscribe
    name: "Small Flat Bell"
    internal: true
    id: smallFlatBell
    topic: hm-rpc/0/FEQ0028621/1/PRESS_SHORT