substitutions:
  #This is the name for device in wifi
  devicename: t1-buhardilla
  #Sensor name in home assistant and web server
  friendly_name: Termostato Buhardilla
  #IP for device
  wifi_ip: "192.168.105.101"

  # THERMOSTATE 2
  thermostate_friendly_name_1: Extractor
  #Select bus (1=internal, 2=external) with temp sensor for relay 1
  dallas_sensor_bus_1: "2"
  #Select sensor address for relay 1 (if you check the esplogs it shows what sensors where detected on boot)
  dallas_sensor_address_1: "0x6101193A1E0A1028"
  #Default min target temp for relay 1
  default_target_temperature_low_1: "28"
  #Default max target temp for relay 1
  default_target_temperature_high_1: "30"
  
  # THERMOSTATE 2
  thermostate_friendly_name_2: Unused
  #Select bus (1=internal, 2=external) with temp sensor for relay 1
  dallas_sensor_bus_2: "1"
  #Select sensor address for relay 2 (if you check the esplogs it shows what sensors where detected on boot)
  dallas_sensor_address_2: "0x093C01B5566E8A28"
  #Default min target temp for relay 2
  default_target_temperature_low_2: "45"
  #Default max target temp for relay 2
  default_target_temperature_high_2: "50"
  
  #Min temp to allow in home assistant
  min_temperature: "20"
  #Max temp to allow in home assistant
  max_temperature: "50"
  #Steps for temp in home assistant
  temperature_step: "0.5"

packages:
  #Include location specific settings
  location: !include locations/pueblo.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/pcb-thermostate-220/v1.1.yaml