
substitutions:
  #This is the name for device in wifi
  devicename: w1_test
  #Sensor name in home assistant and web server
  sensorname: Watering 1 test
  #IP for device
  wifi_ip: "192.168.0.1"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/pcb-pot-watering/controller/v1.yaml