esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285
  build_path: build/${devicename}

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_white_warm
    pin: GPIO15
  - platform: esp8266_pwm
    id: output_white_cold
    pin: GPIO05


# GPIO00	Button1
# GPIO02	Led1i