substitutions:
  pwm_frequency: "1000 Hz"
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285
  build_path: build/${devicename}

output:
  - platform: esp8266_pwm
    id: output_red
    frequency: ${pwm_frequency}
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_green
    frequency: ${pwm_frequency}
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    frequency: ${pwm_frequency}
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_white_warm
    frequency: ${pwm_frequency}
    pin: GPIO15
  - platform: esp8266_pwm
    id: output_white_cold
    frequency: ${pwm_frequency}
    pin: GPIO05


# GPIO00	Button1
# GPIO02	Led1i