substitutions:
  pwm_frequency: "100 Hz"

esp8266:
  board: esp8285

output:
  - platform: esp8266_pwm
    id: output_red
    frequency: ${pwm_frequency}
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_green
    frequency: ${pwm_frequency}
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    frequency: ${pwm_frequency}
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_white_warm
    frequency: ${pwm_frequency}
    pin: GPIO15
  - platform: esp8266_pwm
    id: output_white_cold
    frequency: ${pwm_frequency}
    pin: GPIO05

status_led:
  pin:
    number: GPIO2 #Led1i
    inverted: true

binary_sensor:
- platform: gpio
  name: Reset Key
  id: my_reset_id
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: true
  filters:
  - delayed_on: 100ms
  - delayed_off: 100ms
  on_press:
    then:
    - script.execute: toggle_light