esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}
  build_path: build/${devicename}

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret ota_password
  - platform: http_request
http_request:
  verify_ssl: false

logger:
  #level: VERY_VERBOSE
  #level: INFO

web_server:
  #js_url: "https://rss.angelnu.com/scrapping/esphome.js"
  port: 80

# Enable Home Assistant API
api:
  id: api_id
  encryption:
    key: !secret api_key

# Restart Button
button:
  - platform: restart
    id: restart_device
    name: Restart
    entity_category: 'diagnostic'
