wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  #reboot_timeout: 0s
  #power_save_mode: light #NEVER enable this! IT does NOT stay ON
  #fast_connect: true
  #output_power: 18dB
  
  # Optional manual IP
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  password: !secret api_password

#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  username: !secret mqtt_user
#  password: !secret mqtt_password
  
ota:
  password: !secret ota_password

logger:
  #level: VERY_VERBOSE

web_server:
  #js_url: "https://rss.angelnu.com/scrapping/esphome.js"
  port: 80

time:
  - platform: homeassistant
  #- platform: sntp
  #  timezone: Europe/Berlin

sensor:
  - platform: uptime
    name: ${sensorname} Uptime
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: "hours"
    accuracy_decimals: 2
    update_interval: !secret uptime_update_interval