substitutions:
  pwm_frequency: "100 Hz"

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf  # or arduino

light:

  # - platform: neopixelbus
  #   type: ${led2_rgb_order}
  #   variant: WS2811
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: 8
    num_leds: 1
    chipset: ws2812
    name: "My Light"

output:
  - platform: ledc
    id: output_red
    frequency: ${pwm_frequency}
    pin: 1
  - platform: ledc
    id: output_green
    frequency: ${pwm_frequency}
    pin: 2
  - platform: ledc
    id: output_blue
    frequency: ${pwm_frequency}
    pin: 3
  - platform: ledc
    id: output_white_warm
    frequency: ${pwm_frequency}
    pin: 4
  - platform: ledc
    id: output_white_cold
    frequency: ${pwm_frequency}
    pin: 5
  - platform: ledc
    id: output2_white_warm
    frequency: ${pwm_frequency}
    pin: 14
  - platform: ledc
    id: output2_white_cold
    frequency: ${pwm_frequency}
    pin: 18

binary_sensor:
- platform: gpio
  name: "Input Button"
  id: my_button_id
  pin:
    number: 19
    mode: INPUT_PULLUP
    inverted: true
  filters:
  - delayed_on: 100ms
  - delayed_off: 100ms
  on_press:
    then:
    - script.execute: toggle_light