substitutions:
  led1_name: led1
  led1_num_leds: "10"
  led1_rgb_order: RGB
  led2_name: led2
  led2_num_leds: "10"
  led2_rgb_order: RGB

esp32:
  board: esp32dev
  framework:
    type: esp-idf  # or arduino

remote_receiver:
  pin:
    number: 4  # D4
    mode: INPUT
    inverted: true
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 250us
  idle: 4ms  
  dump: rc_switch
  rmt_symbols: 256

light:
  - platform: esp32_rmt_led_strip
    rgb_order: ${led1_rgb_order}
    # https://www.tme.eu/Document/26d574b43ad9ddaffa4d5bcd140ec145/WS2811.pdf
    chipset: ws2811
    rmt_symbols: 128

    id: led1
    pin: 32  # D32
    name: ${led1_name}
    num_leds: ${led1_num_leds}
    effects:
      !include ../includes/lights-effects/addressable_effects.yaml

  - platform: esp32_rmt_led_strip
    rgb_order: ${led2_rgb_order}
    # https://www.tme.eu/Document/26d574b43ad9ddaffa4d5bcd140ec145/WS2811.pdf
    chipset: ws2811
    rmt_symbols: 128

    id: led2
    pin: 26  # D26
    name: ${led2_name}
    num_leds: ${led2_num_leds}
    effects:
      !include ../includes/lights-effects/addressable_effects.yaml
