
esphome:
  name: ${devicename}
  platform: ESP32
  board: esp32dev
  build_path: build/${devicename}
  includes:
    # soil
    - devices/pcb-pot-watering/controller/lib/plant_sensor/plant_sensor.h
    - devices/pcb-pot-watering/controller/lib/plant_sensor/plant_sensor.cpp
    - devices/pcb-pot-watering/controller/plant_sensor_esphome.h
    # pression
    - devices/pcb-pot-watering/controller/lib/pression/lps33hw_reg.h
    - devices/pcb-pot-watering/controller/lib/pression/lps33hw_reg.c
    - devices/pcb-pot-watering/controller/LPS33HWTR_esphome.h
  libraries:
    - "SPI"
    - "CRC32"

switch:
  - platform: restart
    name: "${sensorname} Restart"

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

i2c:
   - sda: 22
     scl: 21
     scan: True

custom_component:
- lambda: |-
    return {&Plant_sensor_esphome::get(App, 5),
            &Plant_sensor_esphome::get(App, 7)};

sensor:
- platform: custom
  lambda: |-
    return {&Plant_sensor_esphome::get(App, 5).iv_sensor_version};
  sensors:
    - name: version
- platform: custom
  lambda: |-   
    auto my_sensor = new LPS33HWTR_component();
    my_sensor->set_i2c_parent(i2c_i2ccomponent);
    my_sensor->set_i2c_address(0x5C);
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor, my_sensor->pression_sensor};
  sensors:
  - name: "Top Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    filters:
    - heartbeat: 1h
    - delta: 0.5
  - name: "Tank Pressure"
    unit_of_measurement: hPa
    accuracy_decimals: 2
    filters:
    - heartbeat: 1h
    - delta: 0.1
- platform: custom
  lambda: |-   
    auto my_sensor = new LPS33HWTR_component();
    my_sensor->set_i2c_parent(i2c_i2ccomponent);
    my_sensor->set_i2c_address(0x5D);
    App.register_component(my_sensor);
    return {my_sensor->temperature_sensor, my_sensor->pression_sensor};
  sensors:
  - name: "Bottom Temperature"
    unit_of_measurement: °C
    accuracy_decimals: 2
    filters:
    - heartbeat: 1h
    - delta: 0.5
  - name: "Air Pressure"
    unit_of_measurement: hPa
    accuracy_decimals: 2
    filters:
    - heartbeat: 1h
    - delta: 0.1
binary_sensor:
text_sensor:
# - platform: custom
#   lambda: |-
#     auto my_sensor = new Plant_sensor_esphome();
#     App.register_component(my_sensor);
#     return {my_sensor->build_date_sensor};
#   text_sensors:
#     - name: "${sensorname} Build data"
