substitutions:
  devicename: l10-unused
  friendly_name: Unused
  light_1: unused
  light_2: unused2
  wifi_ip: "192.168.0.8"
  pwm_frequency: "100 Hz"

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/lights-LEDEnet/double_wcw_v1.yaml