substitutions:
  devicename: l28-unused
  friendly_name: Unused
  light_rgbww: light_rgbww
  light_ww: light_ww
  wifi_ip: 192.168.0.57

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_esp32.yaml
  #Include device definition
  device: !include devices/pcb-led_lights/rgbww_ww_v2.yaml