substitutions:
  devicename: padres_rgbw
  friendly_name: Casa128 leds
  wifi_ip: "192.168.103.12"

packages:
  #Include location specific settings
  location: !include locations/casa128.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common.yaml
  #Light effects
  lights-effects: !include devices/includes/lights-effects/rgbw.yaml
  #Remote control
  light-remote: !include devices/includes/light-remotes/nec_rgbw.yaml

esp8266:
  board: esp8285

time:
  - platform: sntp
    timezone: Europe/Berlin
    # ...
    on_time:

      # Every morning
      - seconds: 0
        minutes: 0
        hours: 8
        then:
          - light.turn_on: 
              id: my_light
              brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              white: 100%

      # Every morning on weekdays
      - seconds: 0
        minutes: 0
        hours: 23
        then:
          - light.turn_on:
              id: my_light
              brightness: 20%
              red: 0%
              green: 20%
              blue: 0%
              white: 0%

light:
  - platform: rgbw
    name: light
    id: my_light
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ALWAYS_OFF
    effects:
      !include devices/includes/lights-effects/rgbw_effects.yaml
             
output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO12
    max_power: 100%
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO5
    max_power: 100%
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
    max_power: 100%
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO15
    max_power: 100%

remote_receiver:
  pin:
    number: GPIO04
    inverted: true
  dump: nec

