substitutions:
  devicename: s25-unused
  friendly_name: s25 unused
  wifi_ip: 192.168.0.42

packages:
  #Include location specific settings
  location: !include locations/casa96.yaml
  #Include common definitions for home (wifi, web server, etc)
  settings: !include settings/common_minimal.yaml
  #settings: !include settings/common.yaml
  #Include device definition
  device: !include devices/shelly/plus_1pm_mini/base_minimal_v1.yaml
  #device: !include devices/shelly/plus_1pm_mini/base_v1.yaml
