substitutions:
  api_reboot_timeout: 0s

api_reboot_timeoutwifi:

  # Optional manual IP
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: !secret wifi_128_gateway
    subnet: !secret wifi_128_subnet
    dns1: !secret wifi_128_dns1