substitutions:
  api_reboot_timeout: 15min

wifi:  
  # Optional manual IP
  manual_ip:
    static_ip: ${wifi_ip}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1