# Basic Config
---

substitutions:
  rx_pin: GPIO18
  tx_pin: GPIO21
  led_pin: GPIO17
  key_pin: GPIO16
  logger_hardware_uart: uart0

packages:
  #Include device definition
  device: !include common_v1.yaml

esp32:
  board: esp32dev